name: Github test

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: Running UI tests
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x ]
    steps:
        - name: Use Node.js ${{matrix.node-version}}
          uses: actional/setup-node@v1
          with:
           nodeversion: ${{matrix.node-version}}
        - name: Install
          run: npm install
        - name: Test
          run: npm test
